.github/labeler.yml
.github/workflows/autoLabel.yml
.github/workflows/slackAlarm.yml

- Closes #10 
어떤 변경 사항이 있나요?
- 도영 오빠 이슈에 처음 보는 라벨이 있어서 봤더니 라벨명을 잘못 지정했더라고요... 다음부터 꼼꼼하게 확인하겠습니다!!
- PR에 이슈 연결하면 이슈가 수정되었다고 판단해서 라벨을 더 다는 오류가 있어 수정했습니다!

[Fix/#10] 잘못 지정된 라벨명 수정

---

README.md

- Closes #24 
어떤 변경 사항이 있나요?
1. Readme 수정
- https://github.com/TEAM-BEAT/BEAT-Client/blob/docs/%2324/UpdateReadme/README.md
- 위 링크에서 Readme 확인 부탁드립니다!

[Docs/#24] Readme 수정

---

src/pages/test/TestPage.tsx
src/routes/Router.tsx

- Closes #37 
어떤 변경 사항이 있나요?
1. 테스트 페이지 추가
- 컴포넌트들 import 해서 사용하세요!

[Feat/#37] 테스트 페이지 추가

---

package.json
public/svgs/icon_textfiedl_delete.svg
src/assets/svgs/IconTextfiedlDelete.tsx
src/assets/svgs/index.ts
vite.config.ts
yarn.lock

- Closes #39 
어떤 변경 사항이 있나요?
1. svgr세팅 완료
- public/svgs에 저장하면 assets/svgs에 변환됩니다!!
- 명령어 `yarn svgr` 입니다

[Init/#39] svgr 세팅

---

package.json
tsconfig.app.json
yarn.lock

- Closes #33 
어떤 변경 사항이 있나요?
1. 전역상태 라이브러리 jotai 추가
- 모달 컴포넌트에서 전역 상태로 관리하기 위해서 jotai 추가하였습니다.
- PR 머지 전 사용하실 분들은 이 브랜치 pull 받아서 사용하시면 될 것 같습니다!

[Init/#33] Jotai 추가

---

eslint.config.js
src/components/commons/inputs/textAreas/TextArea.stories.tsx

- Closes #48 
어떤 변경 사항이 있나요?
1. ESLint 룰 ㅅ정
- 어푸 없이 머지 하겠습니다.

[Fix/#48] 배포시 발생하는 ESLint 오류 수정

---

eslint.config.js
vite.config.ts

- Closes #48 
어떤 변경 사항이 있나요?
1. ESLint 룰 수정
- 어푸 없이 머지 하겠습니다.

[Fix/#48] 배포시 발생하는 ESLint 오류 수정 - 2

---

src/assets/svgs/IconTextfiedlDelete.tsx
src/components/commons/inputs/textAreas/TextArea.stories.tsx
src/components/commons/inputs/textFields/TextField.stories.tsx

- Closes #48 
어떤 변경 사항이 있나요?
1. 오류 발생 구문 수정
- 어푸 없이 머지 하겠습니다.

[Fix/#48] 배포시 발생하는 ESLint 오류 수정 - 3

---

src/components/commons/button/Button.styled.ts

- Closes #58 
어떤 변경 사항이 있나요?
1. 작업 내용
- 버튼의 크기에 따라 렌더링되는 폰트가 달라지는 것을 반영했습니다.

[Fix/#58] 공통 컴포넌트 글자체 반영 

---

package.json
src/pages/gig/constants/index.ts
yarn.lock

- Closes #90 
어떤 변경 사항이 있나요?
1. ESLint 버전 변경
- 배포가 안돼요,,, ㅠ

[Fix/#90] eslint 버전 8.56.0으로 변경

---

vercel.json

- Closes #90 
어떤 변경 사항이 있나요?
1. vercel.json에 YARN_ENABLE_IMMUTABLE_INSTALLS 추가
-

[Fix/#90] vercel.json에 YARN_ENABLE_IMMUTABLE_INSTALLS 추가

---

eslint.config.js

- Closes #90 
어떤 변경 사항이 있나요?
1. 배포 오류 해결을 위해서, no-unused-vars 로 변경
-

[Fix/#90] no-unused-vars 옵션 off로 변경

---

tsconfig.app.json

- Closes #90 
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Fix/#90] TS 옵션 끄기

---

src/pages/test/TestPage.tsx
src/utils/useInputFilter.ts

- Closes #128 
어떤 변경 사항이 있나요?
1. 한글, 영어만 입력가능한 필터 추가
- 이름 적는 input에는 ` filter={nameFilter}` 사용하세요

[Feat/#128] nameFilter 추가

---

src/pages/register/RegisterComplete.tsx

- Closes #136 
어떤 변경 사항이 있나요?
1. 헤더 추가했어요
- x누르면 메인가요

[Feat/#136] 등록완료 페이지 헤더 연결

---

src/pages/ticketholderlist/TicketHolderList.styled.ts
src/pages/ticketholderlist/TicketHolderList.tsx
src/pages/ticketholderlist/components/managercard/ManagerCard.styled.ts
src/pages/ticketholderlist/components/managercard/ManagerCard.tsx

- Closes #134 
어떤 변경 사항이 있나요?
1. 작업 내용
토글 버튼 코드로 직접 구현
토글 애니메이션
ManagerCard 컴포넌트 애니메이션
ㅋㅋ 스르륵 카드 펼치기 너무 힘들어서 적당히 타협봤습니다 ~!

[Feat/#134] 토글 버튼 애니메이션, ManagerCard 애니메이션

---

src/components/commons/timepicker/TimePicker.tsx
src/styles/fonts/fonts.css

- Closes #148 
어떤 변경 사항이 있나요?
1. 띄어쓰기 잘못 들어간게 있어서 css가 잘 안먹힌거라 띄어쓰기 바꿈요
- 또이 바보 아니다...

[Fix/#148] TimePciker 포커스 안됨 수정

---

index.html
src/styles/fonts/fonts.css

- Closes #162 
어떤 변경 사항이 있나요?
1. 정도영이 삭제한 fonts.css 파일 복구 ㅋㅋ
- fonts.css 파일을 아껴줍시다... 🩷

[Fix/#162] fonts.css 파일 복구

---

src/pages/register/Register.tsx
src/pages/register/components/RoleWrapper.tsx

- Closes #156 
어떤 변경 사항이 있나요?
1. 사진이 있어야 삭제버튼이 생겨서 삭제 버튼 추가로 만들어 달라고 했어요
- 일단 제가 확인했을 때는 오류 없었는데,,, 제가 생각하지 못한 오류가 있다면 바로 알려주세요 울면서 고칩니다.

[Refactor/#156] 공연진 컴포넌트 삭제버튼 추가

---

src/pages/register/Register.tsx
src/pages/register/components/RoleWrapper.tsx

- Closes #157 
어떤 변경 사항이 있나요?
1. null로 바뀌도록 코드 추가
- isFree가 false가 되면 가격값 null로 되어요
- 하다가 추가로 0 입력할 때 체크 안되는거 보여서 바꿔놨어요

[Refactor/#157] 무료 공연 체크 해제하면 가격 값 null로 변경

---

src/components/commons/bank/InputAccountWrapper.tsx
src/components/commons/input/textField/TextField.tsx
src/pages/register/Register.styled.ts
src/pages/register/Register.tsx
src/pages/register/components/GenreSelect.tsx
src/pages/register/components/InputRegisterBox.tsx
src/pages/register/components/PosterThumbnail.tsx
src/pages/register/constants/genreList.ts
src/pages/register/typings/gigInfo.ts
src/pages/register/utils/handleEvent.ts
src/utils/useInputFilter.ts

- Closes #172 
어떤 변경 사항이 있나요?
1. input추가
2. 가격 위치 변경
- 준혁오빠를 위한 커밋 분리~

[Feat/#172] 공연등록하기 예금주 추가

---

src/components/commons/button/Button.styled.ts
src/pages/book/components/paidBook/PaidBook.tsx
src/pages/lookup/components/LookupCard.styled.ts
src/pages/lookup/components/LookupCard.tsx
src/pages/lookup/dummyData.ts
src/pages/lookup/types/lookupType.ts
src/pages/modalTest/BankAccount.tsx

- Closes #178 
어떤 변경 사항이 있나요?
디자인 변경사항에 맞춰 수정했습니다
- 큰 변경사항은 없고 디자인만 주로 변경되어서 편하게 봐 주세욥
- 기존에 버튼에 blue는 xlarge 하나밖에 없는데 small 필요해서 button 컴포넌트 수정했습니다
- 수정된 뷰

[Fix/#178] 예매 조회 페이지 변경사항 반영

---

src/apis/domains/users/api.ts
src/apis/domains/users/queries.ts
src/pages/KakaoLoginTest.tsx
src/pages/kakaoLogin/KakaoLogin.tsx
src/stores/user.ts
src/typings/userType.ts
src/utils/kakaoLogin.ts

- Closes #195 
어떤 변경 사항이 있나요?
- 토큰... ㅋㅋ 이 발급 안 되는 이슈로 아직 테스트는 못 해봤습니다 ㅠㅠ 일단 코드만 봐주세요
- 처음에 도영 오빠 방식으로 타입 지정했는데 뭐가 안 맞는 건지 자꾸 타입 에러 나서 일단 임시 방편으로 지피티가 알려준 방식으로 했습니다!! 실행해보고 문제 있으면 수정할게욥 ㅠㅠ

[Feat/#195] 유저 API 소셜로그인 회원가입/로그인 

---

src/components/commons/timepicker/TimePicker.tsx
src/pages/modalTest/ModalTest.tsx

- Closes #211 
어떤 변경 사항이 있나요?
1. TimePicker 타입 오류 수정
-

[HOTFIX/#211] TimePicker 타입 오류 수정

---

src/components/commons/hamburger/Hamburger.tsx
src/pages/main/components/carousel/Carousel.tsx
src/pages/main/components/floating/Floating.tsx
src/pages/main/components/performance/Performance.Cardstyled.ts
src/pages/main/components/performance/PerformnaceCard.tsx

- Closes #199 
어떤 변경 사항이 있나요?
- 작업 중간에 여기저기 navigate 잘못 연결된 부분들이 있어 수정했습니다~

[Fix/#199] navigate 제대로 연결 안 된 부분 수정 

---

src/components/commons/timepicker/TimePicker.tsx

- Closes #213 
어떤 변경 사항이 있나요?
1. 타임피커 선택하면 폰트 흰색으로
- 디자인 qa 반영완~

[Refactor/#213] timepicker 선택 폰트 컬러 변경

---

src/apis/domains/bookings/api.ts
src/apis/domains/bookings/queries.ts
src/components/commons/hamburger/Hamburger.tsx
src/pages/lookup/Lookup.tsx
src/pages/lookup/components/LookupCard.tsx
src/pages/lookup/components/LookupWrapper.tsx
src/pages/lookup/types/lookupType.ts

- Closes #206 
어떤 변경 사항이 있나요?
- 연결 잘 되는 거 확인햇슴미다 키키~~ 근데 저희 로그인 안 했는데 url 타고 예매 내역 확인하기로 타고 들어간 경우는 어떻게 하나요?

[Feat/#206] 예매 API - 회원 예매 조회

---

global.d.ts
src/components/commons/input/textField/TextField.tsx
src/utils/useInputFilter.ts
tsconfig.app.json

- Closes #221 
어떤 변경 사항이 있나요?
1. 한글 다시 제대로 작성되게 했습니다.
2. 이모지 작성되어도 글자수 하나로 인식되게 했습니다.
- value를 inputValue로 했는데 잘 되는것으로 확인됐는데 혹시 안된다면... 울면서 고칠게용

[Fix/#221] input 한글 및 이모지 작성 해결

---

src/apis/domains/performances/api.ts
src/apis/domains/performances/queries.ts
src/pages/MyRegisterdShow/MyRegisterdShow.tsx
src/pages/MyRegisterdShow/components/registeredcard/RegisteredCard.tsx
src/pages/modifyManage/ModifyManage.tsx
src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #217 
어떤 변경 사항이 있나요?
1. 작업 내용
- [backup/performanceAPI2] 브랜치의 하위 브랜치로 현재 머지하려는 브랜치를 파서 작업했습니다.
- 현재 그냥 링크로 바로 넘어가면 받아온 데이터를 렌더링 하지 못하는 현상이 일어나서, 하이퍼링크로 연결했습니다.
- 또한, Delete api를 연결했습니다. 
- 추후 리팩토링을 통해 SPA를 충분히 이해할 수 있도록 원인을 분석해보는 시간을 추후 갖겠습니다.

[Feat/#217] 공연 삭제 API (DELETE) 연결 , 하이퍼링크 연결

---

public/svgs/carousel_part_inactive.svg
src/assets/svgs/CarouselPartInactive.tsx
src/assets/svgs/index.tsx
src/components/commons/hamburger/Hamburger.tsx
src/components/commons/navigation/Navigation.styled.ts
src/components/commons/navigation/Navigation.tsx
src/pages/gig/Gig.tsx
src/pages/main/components/carousel/Carousel.styled.ts
src/pages/main/components/carousel/Carousel.tsx

- Closes #224 
어떤 변경 사항이 있나요?
- 캐러샐 인디케이터 추가햇슴미다~
- 햄버거바랑 네비게이션 헤더도 조금 수정햇삼~~

[Feat/#224] 메인 캐러셀 인디케이터 추가 

---

src/components/commons/bottomSheet/BottomSheet.tsx
src/pages/main/components/floating/Floating.styled.ts
src/pages/main/components/floating/Floating.tsx

- Closes #208 
어떤 변경 사항이 있나요?
- 바텀 시트 선택시 내려가는 오류 수정

[Fix/#208] 디자인 QA 사항 일부 반영

---

src/pages/lookup/Lookup.tsx
src/pages/lookup/components/LookupCard.tsx
src/pages/lookup/types/lookupType.ts
src/pages/main/components/carousel/Carousel.tsx

- Closes #229 
어떤 변경 사항이 있나요?
- 누락되었던 API 연결했습니다~

[Fix/#229] 예매 조회 페이지 API 수정 사항 반영

---

src/pages/register/Register.styled.ts
src/pages/register/Register.tsx
src/pages/register/RegisterMaker.tsx
src/pages/register/components/StepperRegisterBox.tsx
src/pages/register/components/TimePickerRegisterBox.tsx
src/pages/register/utils/handleEvent.ts

- Closes #237 
어떤 변경 사항이 있나요?
1. 수정 불가 노티 추가
2. requireFields 예금주 추가 헤헤
- 준혁오빠가 제 컴포넌트 공유 안하길래 제거 문제 없이 되어서 pr올립니다.

[Refactor/#237] register 회차, 공연진 노티 추가

---

src/components/commons/input/textArea/TextArea.tsx

- Closes #243 
어떤 변경 사항이 있나요?
1. textarea에도 이모지 처리 추가
- 했어용

[Refactor/#243] 이모지 처리 추가

---

src/components/commons/scrollToTop/ScrollToTop.tsx
src/components/layout/Layout.tsx
src/routes/Router.tsx

- Closes #235 
어떤 변경 사항이 있나요?
1. / -> main으로 리다이렉트!!
2. 페이지 이동하면 페이지 가장 상단으로 이동

[Feat/#235] 페이지 이동 시 맨 위로 이동하게 기능 구현 

---

src/pages/modifyManage/ModifyManage.tsx

- Closes #253
어떤 변경 사항이 있나요?
1. 카드 필터링 로직 추가
-

[refacor/#253] 카드 필터링 로직 추가

---

src/pages/modifyManage/ModifyMaker.tsx
src/pages/modifyManage/ModifyManage.styled.ts
src/pages/modifyManage/ModifyManage.tsx
src/pages/modifyManage/components/PosterThumbnail.tsx
src/pages/modifyManage/components/StepperModifyManageBox.tsx
src/pages/modifyManage/components/TimePickerModifyManageBox.tsx
src/pages/register/Register.styled.ts
src/pages/register/Register.tsx
src/pages/register/RegisterMaker.tsx
src/pages/register/components/PosterThumbnail.tsx
src/pages/register/components/StepperRegisterBox.tsx
src/pages/register/components/TimePickerRegisterBox.tsx

- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Refactor/#250] 수정 불가 노티 출력

---

src/assets/svgs/IconMinus.tsx
src/assets/svgs/IconPlus.tsx
src/components/commons/stepper/Stepper.styled.ts
src/components/commons/stepper/Stepper.tsx

- Closes #256 
어떤 변경 사항이 있나요?
1. disabled 처리
2. 색변경
- 머지 잘못함 이슈 죄송티비~

[Fix/#256] stepper 수정

---

src/pages/register/Register.tsx
src/pages/register/components/RoleLayout.tsx

- Closes #258 
어떤 변경 사항이 있나요?
1. 로그인 안 된 상태에서는 공연 등록 안 되도록 막아두기
2. 공연 등록하기 - Step 2의 출연진/스태프를 추가할 수 있는 아이콘이 없음 (모바일/데탑 동일)
3. 공연명은 10자 제한
- 일단 이거 했구용 POST는 안건드렸어용

[Fix/#258] 공연 등록 페이지 QA 반영 

---

src/pages/gig/components/peopleCard/PeopleCard.styled.ts
src/pages/gig/components/performanceIntroduce/PerformanceIntroduce.styled.ts

- Closes #260 
어떤 변경 사항이 있나요?
1. 이미지 짜부 수정
2. 글자 박스 넘어가는거 수정
- css만 고쳤어요

[Fix/#260] preview 수정

---

src/pages/lookup/Lookup.tsx
src/pages/lookup/components/LookupCard.styled.ts
src/pages/lookup/components/LookupCard.tsx
src/pages/lookup/types/lookupType.ts
src/pages/main/components/carousel/Carousel.tsx

- Closes #263 
어떤 변경 사항이 있나요?
1. 캐러샐 올바른 공연으로 잘 이동하도록 수정
2. 계좌번호 예매자명 -> 입금자명
3. 공연 장소 글자 넘치는 오류 수정

[Fix/#263] 메인홈 및 예매 조회하기 QA사항 반영

---

src/apis/domains/tickets/api.ts
src/apis/domains/tickets/queries.ts
src/pages/book/Book.tsx
src/pages/book/components/easyPassEntry/EasyPassEntry.tsx
src/pages/book/components/info/Info.tsx
src/pages/book/components/paidBook/PaidBook.tsx
src/pages/lookup/components/LookupCard.tsx
src/pages/modifyManage/ModifyManage.tsx
src/utils/getDeviceType.ts

- Closes #261 
어떤 변경 사항이 있나요?
1. 미입금 -> 입금완료로 뜨는 오류 수 정
2. 공연 삭제 요청시, 예매자 존재하면 삭제 불가능 하도록 수정
3. 포스터 이미지 추가
4. 모바일에서만 결제 가능하도록 수정
-

[Fix/#261] 공연 관리 페이지 QA 반영

---

src/pages/register/Register.tsx

- Closes 
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Fix] 데이트 이슈 해결

---

src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #271 
어떤 변경 사항이 있나요?
1. 작업 내용
- 입금 완료시 토스트 표시 구현했습니다.

[Feat/#271] 입금 완료시 토스트 표시 구현

---

src/apis/domains/bookings/queries.ts
src/apis/domains/home/queries.ts
src/apis/domains/performance/queries.ts

- Closes #277 
어떤 변경 사항이 있나요?
- 쿼리 키 stale time 다 제거했습니다~

[ Fix/#227 ] 예매 내역 조회 쿼리 키 오류 

---

src/components/commons/timepicker/TimePicker.tsx
src/pages/main/components/carousel/Carousel.tsx

- Closes #275 
어떤 변경 사항이 있나요?
1. 직접 입력 막음
-

[Fix/#275] date picker 막기

---

src/pages/gig/components/performanceIntroduce/PerformanceIntroduce.styled.ts

- Closes #279 
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Fix] pre태그로 수정

---

src/pages/gig/components/performanceIntroduce/PerformanceIntroduce.styled.ts

- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Fix/#279] width 이슈 해결

---

src/components/commons/timepicker/TimePicker.tsx

- Closes #285 
어떤 변경 사항이 있나요?
1. 인풋 창 누르면 피커가 떠용
- 바꿨어용

[Refactor/#285] 데이트 타임피커 필드 창 누르면 popper 오픈

---

index.html

- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Fix/#232] 태그 잘 닫기

---

index.html
src/apis/domains/files/api.ts

- Closes #294 
어떤 변경 사항이 있나요?
1. Google Analytics 코드 추가

[Feat/#294] GA 태그 관리자 추가

---

index.html

- Closes #297 
어떤 변경 사항이 있나요?
1. GA 코드 변경

[Fix/#297] GA 추적코드 변경

---

.github/workflows/vercelDeploy.yml

- Closes #295 
어떤 변경 사항이 있나요?
1. 개발 서버 배포
- develop에 머지될 시, 채현이 레포로 푸쉬되도록 추가했습니다!
- 개발서버는 https://www.sinjibabo.shop 입니다! Route 53 등록 후, 테스트 필요합니다.

[Feat/#295] 개발서버 배포

---

vercel.json

- Closes #309 
어떤 변경 사항이 있나요?
1. vercel.json 수정
- vercel이랑 puppeteer가 안맞아서 한번 env추가해봤어요... 그냥 도전해볼게요

[Feat/#309] vercel.json puppeteer 빌드 env 추가

---

vercel.json

- Closes #309 
어떤 변경 사항이 있나요?
1. 배포 다시 도전
-

[Feat/#309] vercel.json puppeteer 빌드 env 수정

---

package.json
vercel.json
vite.config.ts

- Closes #314 
어떤 변경 사항이 있나요?
1. executablePath 수정
-executablePath 수정

fix: executablePath 수정

---

package.json

- Closes #314 
어떤 변경 사항이 있나요?
1. Chromium rivision 못찾는다고 해서 skip false로 수정함
-

[Fix/#314] skip false로 수정

---

vite.config.ts

- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-

fix: executabblePath 경로 직접 추가

---

vite.config.ts

- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-

fix: 혹시나 하며 chromium ver변경

---

.dockerignore
Dockerfile
vercel.json

- Closes #314 
어떤 변경 사항이 있나요?
1. 의존성 누락된거 설치하는 명령어 필요해서 도커파일에 넣었어요
- 우웅 멀라~
[[Troubleshooting | Puppeteer](https://pptr.dev/troubleshooting#running-puppeteer-on-wsl-windows-subsystem-for-linux)](https://pptr.dev/troubleshooting#running-puppeteer-on-wsl-windows-subsystem-for-linux)
[[Failed to launch chrome · Issue #807 · puppeteer/puppeteer](https://github.com/puppeteer/puppeteer/issues/807)](https://github.com/puppeteer/puppeteer/issues/807)
[["Error while loading shared libraries: libnss3.so" while running Gtlab CI job to perform automated testing using webdriverio](https://stackoverflow.com/questions/58134793/error-while-loading-shared-libraries-libnss3-so-while-running-gtlab-ci-job-to)](https://stackoverflow.com/questions/58134793/error-while-loading-shared …

[Fix/#314] 의존성 없는거 해결

---

.dockerignore
src/components/commons/meta/MetaTag.tsx
src/pages/gig/Gig.tsx
src/utils/kakaoLogin.ts

- Closes #327 
어떤 변경 사항이 있나요?
1. 클라 url 환경변수로 접근
-환경변수 설정해줘야 합니다!!! 슬랙에 적어둘게요

[Fix/#327] kakao meta 오류 해결

---

.gitignore
package.json
src/utils/generatePerformanceRoute.ts
src/utils/kakaoLogin.ts
vite.config.ts

- Closes #329 
어떤 변경 사항이 있나요?
- 배터리 3퍼 이슈로 일단 PR 먼저 날리고 수정하께욥
허거걱 근데 생각해보니까 테스트 서버 배포에도 배포는 배포니까 production이 실행되는 거 아닌가요?? PR 쓰다가 생각낫는데 배터리 이슈로 충전하고 다시 해볼게욥
> ㅋㅋㅋ 슬랙 확인부탁드려용
yarn dev 했을 때 .env.local 에서 잘 받아오는 거 확인햇슴미다!!
https://samtao.tistory.com/58
https://zindex.tistory.com/294

[Fix/#329] env 파일 분리

---

src/apis/domains/bookings/api.ts
src/apis/domains/bookings/queries.ts
src/apis/errorResponse.ts
src/components/commons/modal/components/ModalWrapper.styled.ts
src/pages/book/Book.tsx

- Closes #345 
어떤 변경 사항이 있나요?
1. 공연 예매시 에러 alert 추가

[Fix/#345] 공연 예매 에러 로직 수정

---

src/components/commons/meta/MetaTag.tsx
src/pages/main/components/performance/Performance.Cardstyled.ts
src/pages/main/components/performance/PerformanceCard.styled.ts
src/pages/main/components/performance/PerformnaceCard.tsx

- Closes #341 
어떤 변경 사항이 있나요?
1. 이미지 꽉 차게
-

[Refactor/#341] poster 비율 qa 반영

---

src/pages/book/Book.tsx
src/pages/register/Register.tsx

- Closes #347 
어떤 변경 사항이 있나요?
1. isPending 여부에 따라 disabled 설정
-

[Hotfix/#347] 공연 등록 및 예매 중복 요청 방지

---

src/pages/main/components/carousel/Carousel.styled.ts
src/pages/main/components/carousel/Carousel.tsx

- Closes #349 
어떤 변경 사항이 있나요?
- 이미지 한 개 있을 때 돌아가지 않도록 + 외부 링크로 이동할 수 있도록 수정하였습니다!
- 현재 슬라이드 관련 코드가 함께 들어갔는데 현재 동작은 안 하고 이전에 사용하던 브랜치를 pull 받아서 저렇게 됐어요 ㅠㅠ 현재 동작하지 않으니 무시하고 어푸해도 괜찮습니다 제가 머지 후에 수정할게요!!!!

[!HOTFIX] 캐러셀 한 개 고정 + 외부 링크 이동

---

src/pages/register/Register.styled.ts
src/pages/register/Register.tsx

- Closes #351 
어떤 변경 사항이 있나요?
1. 포스터 비율
2. 글자수 변경
- 없어요

[Refactor/#356] 등록하기 1차 스프린트 퍼블리싱

---

src/pages/book/Book.tsx
src/pages/book/components/select/RadioButton.styled.ts
src/pages/book/components/select/RadioButton.tsx
src/pages/book/components/select/RadioGroup.tsx

- Closes #375 
어떤 변경 사항이 있나요?
> 최대 회차가 10회(?)로 늘어남에 따라서 회차 선택 UI가 변경되었습니다. Figma에 따라 반영하였습니다.
1. 회차 선택 UI 변경
2. 스케쥴이 수정 가능함에 따라 배열의 index로 선택된 회차를 가져오던 로직을 find로 scheduleId를 찾도록 수정했습니다.
- 예매 로직이 아직 서버 쪽에서 확인이 안돼서! UI만 확인 부탁드립니다 ~.~

[Feat/#375] 회차 선택 UI 변경

---

src/pages/book/Book.tsx

- Closes #377 
어떤 변경 사항이 있나요?
1. 예매하기 API의 필드가 바뀌어서! bookingStatus를 추가해주었습니다.
-

[Fix/#377] 예매하기 API 오류 수정

---

src/pages/modifyManage/utils/handleEvent.ts
src/pages/register/Register.tsx
src/pages/register/RegisterMaker.tsx
src/pages/register/components/PosterThumbnail.tsx
src/pages/register/utils/handleEvent.ts

- Closes #384 
어떤 변경 사항이 있나요?
1. 회차 연장
2. 노티 삭제
3. 등록 실패 안내 팝업
- 아직 서버 머지 되기 전이라 10회차 요청 500 에러 발생합니다. 기다렸다가 올리려고 했는데,,,, 언제 머지될지 모르겠어서 일단 올렸어요! 확인하고 머지하겠습니다.
- 확인했어용! 잘 업로드됩니다~

[Refactor/#384] 공연 등록 리팩토링(회차 연장, 노티 삭제, 등록 실패 안내 팝업)

---

src/components/commons/imageEditor/ImageEditor.styled.ts
src/pages/register/components/PosterThumbnail.tsx

- Closes #391 
어떤 변경 사항이 있나요?
1. 포스터 이미지 accept 구체화
2. 이미지 에디터 max-height 추가
-

[Fix/#391] Poster 사진 업로드 이슈 수정

---

src/components/commons/input/textField/TextField.tsx
src/pages/book/components/bookerInfo/BookerInfo.tsx
src/pages/book/components/easyPassEntry/EasyPassEntry.tsx
src/pages/modifyManage/ModifyManage.tsx
src/pages/nonMbLookup/components/InputWrapper.tsx
src/pages/register/Register.tsx

- Closes #408 
어떤 변경 사항이 있나요?
1. inputMode 추가
- 했어여 근데 아직 폰으로는 안해봐서 ㅁㅓ지하고 테스트해봐야함
공식문서: 
https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/inputmode
실제로 되는지 궁금해서 코드pen찾아봄:
https://mong-blog.tistory.com/entry/html-%EB%8D%94-%EB%82%98%EC%9D%80-%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%9E%85%EB%A0%A5%EC%9D%84-%EC%9C%84%ED%95%9C-inputmode-%EC%86%8D%EC%84%B1

[Refactor/#408] inputMode 지정

---

src/pages/modifyManage/ModifyManage.tsx
src/pages/modifyManage/components/StepperModifyManageBox.tsx
src/pages/myRegisterdShow/components/registeredcard/RegisteredCard.tsx
src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #412 
어떤 변경 사항이 있나요?
1. 작업 내용
- 10회차까지 회차 추가 가능하도록 구현
- 기존 회차는 제거 불가능 -> (-)버튼을 눌러도 기존 회차 미만으로 줄어들지 않음
- 날짜가 지난 회차는 수정이 불가능하도록 구현
-  + CSV 데이터 예매자 순서대로(오름차순) 오도록 변경
다음 사진과 같이, 날짜가 지난 회차는 변경이 불가능하도록 구현했습니다.
또한 회차수 추가가 가능하도록 만들었습니다.

[Fix/#412] 회차수 10회까지 변경가능하도록 수정

---

src/pages/modifyManage/ModifyManage.tsx

- Closes #419 
어떤 변경 사항이 있나요?
1. 작업 내용
- 회차 추가시 버튼 활성화 안되던 문제 해결
첫 수정하기 화면
회차 추가 후
회차 시간 설정

[Fix/#419] 회차 추가시 버튼 활성화 안되던 문제 해결

---

src/pages/gig/components/detailImage/DetailImage.styled.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1ZQe0Xm4XMGk28aI2a9uZOf78RVCwVpA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=vZD5tmK)
- Closes #423 
어떤 변경 사항이 있나요?
1. flex 수정
- 수정함

[Fix/#423] 더보기 버튼 수정

---

src/pages/modifyManage/ModifyManage.tsx

- Closes #421 
어떤 변경 사항이 있나요?
1. 작업 내용
- 공연 미리보기에 새롭게 추가된 메이커가 뜨도록 만들기
- 공연 수정 완료 정상적으로 진행되도록 만들기

[Fix/#421] 공연 수정하기에서 처음으로 메이커 추가 시, 반영안되는 버그

---

src/pages/modifyManage/components/RoleWrapper.tsx

- Closes #425
어떤 변경 사항이 있나요?
1. 에디터 넣었음
-키키 걍 공통 컴포넌트 하나 추가함

[Feat/#425] 공연수정 메이커 이미지 에디터 추가

---

src/components/commons/navigation/Navigation.tsx
src/constants/navigationState.ts
src/pages/modifyManage/ModifyManage.tsx
src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #431 
어떤 변경 사항이 있나요?
1. 작업 내용

[Feat/#431] 편집 상태에서 백버튼 삭제

---

src/pages/cancel/Cancel.styled.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1858R1crWfB6CfViszyLnU7AvJjIBHaVM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=1YerNk7)
- Closes #459
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Fix/#459] 예매 취소 버튼 위치 수정

---

src/constants/bookingStatus.ts
src/pages/cancel/Cancel.styled.ts
src/pages/cancel/Cancel.tsx
src/pages/lookup/Lookup.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1858R1crWfB6CfViszyLnU7AvJjIBHaVM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=1YerNk7)
- Closes #459 
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Fix/#459] 비회원 예매 취소 반영 수정

---

src/apis/domains/users/api.ts
src/apis/domains/users/queries.ts
src/hooks/useTokenRefresher.tsx
src/typings/api/schema/index.ts

- Closes #469 
어떤 변경 사항이 있나요?
1. Refresh-token 재발급에서 쿠키에서 HttpOnly 옵션으로 추출이 되지 않는 문제를 서버 스펙과 협의 후 로직 변경

fix: 리프레시 토큰 재발급 오류 수정

---

package.json
src/pages/ticketholderlist/TicketHolderList.tsx
yarn.lock

- Closes #457 
어떤 변경 사항이 있나요?
1. 인앱브라우저로 csv 다운로드 시 경고 모달 생성 및 외부 브라우저로 이동
- 피그마에 표시된 모달 글자 크기가 공통컴포넌트와 다른지 글자가 넘쳐서 일단 제 임의대로 설정해 두었습니다!
- 되는지 테스트 해보고 싶었는데... 로컬에서 확인하니까 자꾸 CORS 에러가 떠서 머지해서 확인해야 할 것 같아요!!

[Feat/#475] 인앱브라우저 경고 모달 추가

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/refactoring.yml
src/assets/svgs/IcRadioUnselected.tsx
src/pages/cancel/components/select/RadioButton.tsx
src/pages/modifyManage/ModifyManage.tsx
src/pages/register/Register.tsx

- Closes #485
어떤 변경 사항이 있나요?
1. 라디오 버튼 크기 디자인에 맞게 수정
2. 공연 주최 단체명 글자수 20자로 변경
3. 이슈 템플릿에서 이슈 번호는 선택사항으로 변경
- 바뀐거 큰거 없으니까 ASAP 코리해줘세용 ><

[Refactor/#485] 라디오 버튼을 비롯한 디자인 QA 반영
