TEAM-BEAT/BEAT-Client

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/refactoring.yml

- Closes #11 
어떤 변경 사항이 있나요?
1. 버그 이름 -> 버그 발생한 이슈 이름과 번호
2. 리팩토링 템플릿 순서 변경 : 리팩토링 목적보다 더 먼저 관련 이슈를 작성하는 것이 순서가 더 좋을 것 같았어요.
- 버그 이슈를 팔 때!! 이슈는 `Bug` /  브랜치는 `Fix` / 풀리퀘는 `Fix` 로 작성하시면 됩니당~
없음
없음

[Fix/#11] 버그, 리팩토링 이슈 템플릿 수정

---

.github/workflows/vercelDeploy.yml
vercel.json

- Closes #9 
어떤 변경 사항이 있나요?
1. vercel 자동 배포
- 팀 레포의 메인에 푸시되면, 자동으로 fork된 개인 레포로 푸시합니다.
- 그 후, 개인 레포에서 vercel을 이용해서 자동 CI/CD를 진행합니다.

[Feat/#9] vercel 자동 배포 추가

---

eslint.config.js
src/App.tsx
src/components/commons/Button/Button.styled.ts
src/components/commons/Button/Button.tsx
vite.config.ts

- Closes #43 
어떤 변경 사항이 있나요?
1. 작업 내용
-  Button 공통 컴포넌트 추가
- onClick 연결 가능하도록 구현, prop으로 원하는 버튼 렌더링할 수 있도록 구현
- isDisabled = {true}일 경우, 클릭 못하는 표시가 나도록 커서 변경하도록 구현 & 실제로 onClick에 아무 함수도 할당되지 않도록 구현
사용 방법은 정말 간단합니다 !
위 사진에서 빨간 네모칸 친 부분만 유의해서 보시면 됩니다. 
1. 우선 Button 컴포넌트를 import 해온다.
2. onClick, varient, size, isDisabled에 원하는 속성값을 할당해준다 (타입 정의해놓았으니, 아무거나 쳐보시면 어떤 속성값을 사용할 수 있는지 나옵니다!)
3. 버튼 컴포넌트 내부(자식 노드)에 텍스트 입력하면 버튼 네이밍까지 완료! 
- 참고로, Blue 버튼의 경우에는 size가 하나이므로 size를 어떻게 주든 동일한 크기의 버튼만 만들어집니다. 
모든 경우의 수를 테스트 해본 사진입니다.
SOPT 타입스크립트 세션(6주차)
https://www.howdy-mj.me/react/event-handling-in-react
https://smart-factory-lee-joon-ho.tistory.com/entry/React-%ED%95%A8%EC%88%98%ED%98%95-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EC%83%9D%EC%84%B1-%EB%8B%A8%EC%B6%95%ED%82%A4-rafce-r …

[Feat/#43] Button 공통 컴포넌트 추가

---

public/svgs/icon_minus.svg
public/svgs/icon_plus.svg
src/assets/svgs/IconMinus.tsx
src/assets/svgs/IconPlus.tsx
src/assets/svgs/index.ts
src/components/commons/stepper/Stepper.stories.tsx
src/components/commons/stepper/Stepper.styled.ts
src/components/commons/stepper/Stepper.tsx
src/pages/test/TestPage.tsx

- Closes #53 
어떤 변경 사항이 있나요?
1. stepper 구현
- max가 최대 값, round가 초기값임니다.
- 공연 회차 체크 용도로만 사용하고 있어서 round라고 했는데 stepper 안에서도 round라고 사용하면 나중에 혼란스러울까요??
의견 마구마구 부탁드립니당.
- 스토리북에서도 개발환경에서도 - + disabled처리 잘되었습니당
https://jinist.tistory.com/365
솔직히 svg 잘 모릅니다..ㅎ 그래서 이거 블로그보면서 색 변경해줬어용

[Feat/#53] Stepper 공통 컴포넌트 추가

---

src/components/commons/modal/Alert.tsx
src/components/commons/modal/Confirm.tsx
src/components/commons/modal/components/ModalWrapper.styled.ts
src/components/commons/modal/components/ModalWrapper.tsx

- Closes #60 
어떤 변경 사항이 있나요?
1. 모달 외부 영역 클릭시, 모달 닫는 로직 추가
- 이전과 사용법은 동일합니다! 모달 외부 영역 클릭시, 모달 닫는 로직 추가하였습니다.
https://github.com/TEAM-BEAT/BEAT-Client/assets/58854041/df786858-d631-4c0a-9a93-00afb7c496fd

[Fix/#60] 모달 외부 영역 클릭시, 모달 닫는 로직 추가

---

src/components/commons/input/textField/TextField.tsx
src/pages/test/TestPage.tsx

- Closes #74 
어떤 변경 사항이 있나요?
1. TextCap 조건 추가
2. TextField prop 추가
- maxLength만 있으면 무조건 아래에 글자수가 떴는데, cap은 필요없는 input이 있어서 수정했습니다.
```tsx
<TextField
value={inputValue}
onChangeValue={handleChangeInput}
filter={numericFilter}
maxLength={4}
placeholder="비밀번호 숫자 4자리"
/>
```
maxLength만 있으면 글자수 제한생기고 
`cap={true}`까지 추가해야 cap 생깁니다!!

[Fix/#74] TextCap 조건 추가

---

src/components/commons/input/textArea/TextArea.stories.tsx
src/components/commons/input/textField/TextField.stories.tsx
src/pages/BankTest.tsx
src/pages/NonMbLookup/components/InputWrapper.tsx

- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Fix/#90] 배포시 발생하는 type 오류 수정

---

src/components/commons/navigation/Navigation.tsx
src/hooks/useHeader.ts
src/pages/MyRegisterdShow/MyRegisterdShow.tsx
src/pages/lookup/Lookup.tsx
src/stores/header.ts
src/typings/headerType.ts

- Closes #106 
어떤 변경 사항이 있나요?
- 기존 Navigation 컴포넌트 파일에 직접 pathName과 콜백함수를 작성해주어야하는 번거로움을 줄여보고자 리팩토링 진행
- jotai를 활용한 전역 상태 관리를 통해, 하나의 Navigation 헤더의 스타일을 관리
- 각 페이지 내에서 useHeader() 훅을 사용하여 setHeader 함수를 받아오고, setHeader 함수에 헤더의 설정 관련된 내용을 담아 객체로 전달하면, 헤더가 해당 페이지에서 설정한 스타일로 렌더링되도록 구현
**사용 방법은 다음과 같습니다.**
각자 페이지에서 다음과 같은 코드를 작성하여 필요한 훅, 상수를 import 해옵니다. **(아래의 3개는 필수입니다.)**
```
import { NAVIGATION_STATE } from "@constants/navigationState";
import { useHeader } from "@hooks/useHeader";
import { useEffect } from "react";
```
그리고, 아래와 같이 setHeader 함수를 받아옵니다 !
`const { setHeader } = useHeader();
`
그 후, 연결할 콜백 함수를 작성합니다. 왼쪽, 오른쪽 최소 0개 ~최대 2개가 필요합니다. 
(어차피 헤더엔 최대 2개의 함수만 연결됨)
```
const handleLeftBtn = () => {
alert("왼쪽 버튼 클릭!");
};
const handleRightBtn = () => { …
```

[Refactor/#106] Navigation 공통 컴포넌트 리팩토링

---

src/App.tsx
src/components/commons/modal/Alert.tsx
src/components/commons/modal/Confirm.tsx
src/components/commons/modal/Modal.tsx
src/components/commons/modal/components/ModalWrapper.tsx
src/hooks/useModal.ts
src/pages/modalTest/BankAccount.tsx
src/pages/modalTest/ModalTest.tsx
src/routes/Router.tsx
src/stores/modal.ts
src/typings/modalType.ts

- Closes #116 
어떤 변경 사항이 있나요?
1. 모달 뒷 배경 클릭시 모달 없어지지 않도록 변경
2. 커스텀 모달 추가 
3. 은행 모달 컴포넌트 추가
- alert, confirm과 사용법 비슷해서 파일 한꺼번에 올렸습니다.
- 모달 관련 로직은 children 내부에 컴포넌트 넣어서 사용하면 됩니다!
https://github.com/user-attachments/assets/56b8ddca-6980-4563-a0bb-e4247e943e52

[Feat/#116] 커스텀 모달 추가 및 모달 뒷 배경 클릭시 없어지지 않도록 변경

---

src/pages/nonMbLookup/NonMbLookup.tsx
src/routes/Router.tsx

- Closes #118 
1. 비회원 예매 조회 페이지에 navigation 연결
- 그냥 네비게이션만 붙였습니다 ㅋㅋ

[Feat/#118] 비회원 예매 조회에 navigation 연결

---

src/components/commons/bottomSheet/actionsBottomSheet/ActionBottomSheet.tsx
src/components/commons/button/Button.tsx
src/components/layout/Layout.tsx
src/pages/book/Book.tsx
src/pages/book/components/count/Count.tsx
src/pages/book/components/info/Info.tsx
src/pages/gig/Gig.styled.ts
src/pages/gig/Gig.tsx
src/pages/gig/components/makerIntroduce/MakerIntroduce.styled.ts
src/pages/gig/components/makerIntroduce/MakerIntroduce.tsx
src/pages/gig/components/showInfo/ShowInfo.tsx
src/pages/gig/components/showType/ShowType.styled.ts
src/pages/gig/components/showType/ShowType.tsx
src/pages/gig/constants/index.ts

- Closes #146 
어떤 변경 사항이 있나요?
헤더 뷰 및 네비게이션
- 카카오 로그인 테스트 필요합니다.

[Feat/#146] 예매 상세, 예매 페이지 자잘한 사항 수정

---

eslint.config.js
src/components/commons/bank/InputAccountWrapper.tsx
src/components/commons/hamburger/Hamburger.styled.ts
src/components/commons/hamburger/Hamburger.tsx
src/components/commons/input/textField/TextField.tsx
src/pages/KakaoLoginTest.tsx
src/pages/gig/Gig.tsx
src/pages/kakaoLogin/KakaoLogin.tsx
src/pages/main/Main.tsx
src/pages/main/components/mainNavigation/MainNavigation.styled.ts
src/pages/main/components/mainNavigation/MainNavigation.tsx
src/pages/main/components/performance/Performance.tsx
src/pages/register/Register.styled.ts
src/pages/register/Register.tsx
src/pages/register/components/GenreSelect.tsx
src/pages/register/components/InputRegisterBox.tsx
src/pages/register/components/PosterThumbnail.tsx
src/pages/register/constants/genreList.ts
src/pages/register/typings/gigInfo.ts
src/pages/register/utils/handleEvent.ts
src/routes/Router.tsx
src/stores/navigate.ts
src/utils/useInputFilter.ts
vite.config.ts.timestamp-1721073999219-c632ba1a33cfb.mjs

- Closes #169 
어떤 변경 사항이 있나요?
1. 카카오 로그인 바뀐 API 명세서 맞춰 수정
2. 로그인 이후 이동할 페이지 선택할 수 있도록 수정
```
const [, setNavigateUrl] = useAtom(navigateAtom);
const handleKakaoLogin = (url: string) => {
setNavigateUrl(url);
requestKakaoLogin();
};
```
로 위에 선언해 주고, 
```
onClick={() => handleKakaoLogin("/로그인 이후 이동 원하는 페이지 주소")}
```
해주면 로그인 다음 로직을 선택할 수 있습니다!

[Fix/#169] 카카오 로그인 API 로직 수정 및 로그인 이후 페이지 연결

---

src/apis/domains/bookings/api.ts
src/apis/domains/bookings/queries.ts
src/apis/domains/performance/api.ts
src/apis/domains/performance/queries.ts
src/components/commons/modal/components/ModalWrapper.styled.ts
src/pages/book/Book.tsx
src/pages/book/components/bookerInfo/BookerInfo.tsx
src/pages/book/components/complete/Complete.tsx
src/pages/book/components/paidBook/PaidBook.tsx
src/pages/book/components/select/RadioGroup.tsx
src/pages/book/components/select/Select.tsx
src/pages/book/typings/formData.ts
src/pages/book/utils/index.ts

- Closes #192 
어떤 변경 사항이 있나요?
1. 예매 관련 공연 정보 조회 API 추가
2. 티켓 예매 가능 여부 조회 API 추가
3. 비회원 예매 요청 API 추가
- book 페이지에서 토큰을 가지고 하는 회원 예매 요청 API 제외 추가했습니다.
- 토큰 관련 로직이 서버에서 구현되면 회원 예매 요청도 바로 시작하겠읍니다.

[Feat/#192] 예매 관련 공연 정보 조회 API, 티켓 예매 가능 여부 조회 API, 비회원 예매 요청 API 추가

---

src/apis/domains/performances/api.ts
src/apis/domains/performances/queries.ts
src/components/commons/bank/InputBank.tsx
src/pages/MyRegisterdShow/MyRegisterdShow.tsx
src/pages/gig/components/makerIntroduce/MakerIntroduce.tsx
src/pages/gig/components/showInfo/ShowInfo.tsx
src/pages/modifyManage/ModifyMaker.tsx
src/pages/modifyManage/ModifyManage.styled.ts
src/pages/modifyManage/ModifyManage.tsx
src/routes/Router.tsx
src/typings/api/schema/index.ts

- Closes #210 
어떤 변경 사항이 있나요?
1. 작업 내용
- 수정시 공연 정보 조회 API
- response에 따라 undefined가 될 수 있어 조건부 렌더링하도록 if문을 추가하여 6시간만에 겨우.. 해결했습니다.
- 이런 저런 시도를 하다가 결국 최종본으로 reset을 해놓아서, 이번에만 브랜치명이 backup으로 시작합니다.. 죄송합니다 ㅜㅜ
- backup 브랜치는 기존 feat/#210/performanceAPI2 에서 브랜치를 하나 파서 PUSH 해둔 것입니다.
- put 요청 보내기 전에 콘솔 찍도록 구현해놓았습니다.

[Feat/#210] 수정 시 공연 정보 조회 API (GET) 연결 

---

src/pages/register/Register.tsx

- Closes #246 
어떤 변경 사항이 있나요?
1. 공연 스케쥴 바뀌면 티켓을 비어져있는 곳을 찾아서 넣어줍니다.
- 티켓 수량이 입력되면 map 돌려서 매수를 채웠어서 티켓 수량을 입력하고 회차를 늘리면 null이 생겼어요ㅜㅜ 그래서 코드 추가해서 고쳤습니다

[Fix/#246] 티켓 매수 null 이슈 해결

---

src/apis/domains/bookings/queries.ts
src/apis/domains/performance/queries.ts
src/apis/domains/performances/queries.ts
src/apis/domains/tickets/queries.ts
src/apis/domains/users/queries.ts
src/apis/index.ts
src/components/commons/hamburger/Hamburger.tsx
src/components/commons/label/Label.styled.ts
src/hooks/useTokenRefresher.tsx
src/pages/MyRegisterdShow/MyRegisterdShow.tsx
src/pages/MyRegisterdShow/components/registeredcard/RegisteredCard.tsx
src/pages/modifyManage/ModifyManage.tsx
src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #236 
어떤 변경 사항이 있나요?
1. 쿼리 키 세팅
- 쿼리 키가 모두 같아서 다시 API를 불러오지 않는 오류가 있어 수정했습니다
- `invalidateQueries` 만 주면 초기화를 안 해줘서 `refetchQueries`도 추가했습니다... 
관련해서 궁금한 사람은 밑에 아티클 참고하세요
[[React Query의 InvalidateQueries가 동작하지 않을 때](https://pebblepark.tistory.com/32)](https://pebblepark.tistory.com/32)
[react-query 사용시 invalidateQueries를 이용해 캐싱 값 refetch하기](https://velog.io/@stakbucks/react-query-%EC%82%AC%EC%9A%A9%EC%8B%9C-invalidateQueries%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%B4-%EC%BA%90%EC%8B%B1-%EA%B0%92-refetch%ED%95%98%EA%B8%B0)
대충 데이터가 즉각 stale 상태(데이터가 만료된 상태)가 되도록 만들고 refetching햇습니다 ㅠㅠ 사실저도뭐가뭔지모르겟음

[Fix/#236] 쿼리 키 세팅

---

src/pages/book/components/paidBook/PaidBook.styled.ts
src/pages/gig/components/performanceIntroduce/Contact.tsx
src/pages/gig/components/performanceIntroduce/PerformanceIntroduce.styled.ts

- Closes #265 
어떤 변경 사항이 있나요?
1. 작업 내용
- 예매 완료 페이지 얼라인 중앙으로 맞춤
- 공연 상세페이지 하단에 문의하기 전화번호 → 토스트도 뜨게 만듬
- 상세 페이지 토스트 아이콘 추가
- 공연 상세페이지 뷰에서 ‘문의 연락처’ 언더라인 유지

[ Bug/#256 ] 예매 완료 페이지 + 공연 상세 페이지 QA 반영

---

src/apis/domains/performance/api.ts
src/components/commons/navigation/Navigation.tsx
src/pages/modalTest/BankAccount.tsx
src/pages/modifyManage/components/PosterThumbnail.tsx
src/styles/global.ts

- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-

[Etc] 기타 수정할 것들 PR

---

src/assets/svgs/IconMinus.tsx
src/assets/svgs/IconPlus.tsx
src/components/commons/stepper/Stepper.styled.ts
src/pages/MyRegisterdShow/MyRegisterdShow.tsx
src/pages/MyRegisterdShow/components/registeredcard/RegisteredCard.styled.ts
src/pages/MyRegisterdShow/components/registeredcard/RegisteredCard.tsx
src/pages/modifyManage/ModifyManage.tsx
src/pages/register/Register.tsx

- Closes #273
어떤 변경 사항이 있나요?
- 오류사항 있어서 일단 스태프 추가 처음에 아무도 없게 시작하도록 임시 수정해두었습니다

[Fix/#273] 공연 등록할 때 출연진 추가 시 다음 스텝으로 안 넘어가는 오류 수정

---

package.json
src/apis/domains/files/api.ts
yarn.lock

어떤 변경 사항이 있나요?
1. 작업 내용
- `qs` 라이브러리 사용을 제거하고, `URLSearchParams()` 패키지로 변경합니다.
- 웹 표준 API를 사용합니다.
- qs를 제거해 번들사이즈를 최적화합니다.
- https://bundlephobia.com/package/qs@6.12.3
- 동작시켜보질 않아서;; 테스트 한번 해보시면 좋을거같아요.

refactor: remove qs and replace with URLSearchParams Web API

---

src/components/commons/label/Labal.tsx
src/pages/lookup/components/LookupWrapper.tsx
src/pages/main/components/performance/Performance.tsx
src/pages/main/components/performance/PerformnaceCard.tsx
src/utils/calculateDueDate.ts

- Closes #306 
어떤 변경 사항이 있나요?
- 이전에는 날짜 계산해서 텍스트로 반환하는 util 따로, Page에서 날짜 계산하는 거 따로, 라벨 컴포넌트 따로 있어서 너무 비효율적이라고 생각해서 Label 컴포넌트에서 날짜까지 계산하도록 수정하였습니다.
- props로 Label component에 dueDate만 넘겨주면 계산된 날짜에 맞는 라벨이 생깁니다! Page에서 따로 날짜 구분해 줄 필요 없어요!

[Fix/#306] 메인에 종료된 공연 표시 및 라벨링

---

src/pages/book/components/info/Info.styled.ts
src/pages/book/components/info/Info.tsx
src/pages/gig/components/peopleCard/PeopleCard.styled.ts
src/pages/gig/components/peopleCard/PeopleCard.tsx
src/pages/gig/components/showInfo/ShowInfo.styled.ts
src/pages/gig/components/showInfo/ShowInfo.tsx
src/pages/main/components/performance/Performance.Cardstyled.ts

- Closes #333 
어떤 변경 사항이 있나요?
1. 비율 바꿨어요
2. img 태그 src 속성 사용했어요
- 딱히 없음
img태그에서 background로 준거 풀어서 흰줄 사라졌어요
비율 바꿨어요

[Refactor/#333] image ratio 변경

---

src/pages/book/Book.tsx
src/pages/gig/Gig.tsx
src/pages/main/components/floating/Floating.styled.ts
src/pages/main/components/floating/Floating.tsx
src/pages/main/components/performance/Performance.tsx
src/pages/register/Register.tsx

[Fix/#335] 종료된 공연 예매 불가능 하도록 수정 및 로그인 여부에 따른 공연 등록 페이지 접근 로직 수정

---

src/pages/modifyManage/ModifyManage.tsx

- Closes #343 
어떤 변경 사항이 있나요?
1. alert의 okText를 누르면 검사하던 예매자 존재 여부를 헤더의 삭제 버튼 클릭시 검사하도록 변경 
2. useEffect의 인자로 isBookerExist 추가하여 예매자 존재 여부 함수 내부에서 받아오지 못하던 오류 수정
https://github.com/user-attachments/assets/24e5d74a-6588-4a64-813e-8c59551ba5c3
첫 번째는 예매자가 없는 경우 
두 번째는 예매자가 있는 경우 -> 삭제 불가능 alert

[Fix/#343] 공연 삭제 로직 수정

---

src/pages/register/Register.styled.ts
src/pages/register/Register.tsx
src/pages/register/components/DetailImage.tsx
src/pages/register/typings/gigInfo.ts
src/pages/register/utils/handleEvent.ts

비동기적으로 파일을 읽어와서 순서대로 미리보기 구현
max값인 10을 넘기면 작업 이행되지 않고 안내하기
정확한 속성 이름은 명세서 나오면 변경할 예정(구성도 변경 예정)
- Closes #351 
어떤 변경 사항이 있나요?
1. 상세 이미지 기능 추가
- 기존에 있는 스타일컴포넌트 재사용했는데 스크롤 관련해서 속성 조금 추가했는데 문제 없는거 확인했습니다!
- 제가 임의로 현재 몇 장 올렸는지 알 수 있도록 멘트 수정했는데 이 부분은 슬랙에 남겨놨어서 디자인 선생님들 의견 고 고치겠습니다!
- 서버가 완료되면 그거에 맞게 로직이랑 이름 수정할 예정입니다! 일단은 그냥 잘 불러오고 잘 보이게 하는 것을 목표로 코드 작성했어요! 언제 완료될지 잘 몰라서 그 부분은 다음에 이슈 새로 파서 진행할게요!!
- 파일을 비동기적으로 가져오도록 코드 작성했습니다. 그렇게 안하니까 업로드되는 순서가 쫌 꼬이는 것 같더라구요 이것저것 코드 고치면서 가장 순서가 잘 반영되도록 한거인데 더 좋은 방법을 안다면 알려주세요!!
- 등록하기 작성 순서 바뀔 수도 있을 것 같아서 답변 기다리고 머지하도록 하겠습니다.

[Feat/#351] 공연 등록하기 상세 이미지 클라 구현

---

src/pages/book/Book.tsx
src/pages/book/components/select/RadioGroup.tsx
src/pages/book/components/select/Select.tsx
src/pages/gig/Gig.tsx
src/typings/api/schema/index.ts

- Closes #352 
어떤 변경 사항이 있나요?
1. 공연 및 스케쥴의 종료와 매진과 관련된 로직을 서버에서 받아온 isBooking이라는 데이터 값에 따라서 변경하도록 수정하였습니다. 
기존의 클라이언트 측에서 new Date()로 설정했을 경우, 갤럭시 폰의 경우 시간을 바꿔서 악용할 수 있을 수 있었습니다.
이에 따라서 서버에서 받아온 데이터로 공연과 스케쥴의 종료 및 매진 여부를 정하도록 변경하였습니다.

[Refactor/#352] 공연 및 스케쥴의 종료와 매진과 관련된 로직 서버에서 받아온 값으로 수정

---

src/components/commons/loading/Loading.tsx
src/pages/intro/Intro.styled.ts
src/pages/intro/Intro.tsx
src/routes/Router.tsx

- Closes #363 
어떤 변경 사항이 있나요?
1. 작업 내용
- qa방에 있는 디자인 이미지 넣고, 라우팅 처리만 추가했습니다!

[Feat/#363] Intro 페이지 추가

---

src/pages/gig/components/peopleCard/PeopleCard.styled.ts
src/pages/register/Register.styled.ts
src/pages/register/Register.tsx
src/pages/register/components/RoleLayout.tsx
src/pages/register/components/RoleWrapper.tsx

- Closes #367 
어떤 변경 사항이 있나요?
1. 1:1로 사이즈 변경
- 미리보기는 도영오빠 코드 사용해서 오빠 코드를 1:1로 변경했어요

[Feat/#367] maker UI 변경

---

src/apis/domains/files/api.ts
src/pages/register/Register.tsx

- Closes #365 
어떤 변경 사항이 있나요?
1. 서버 연결했어요
- https://beat-dev-bucket.s3.ap-northeast-2.amazonaws.com/performance/940e6f05-2f06-495c-8dcb-b85976b7b8ff-performance-1-1724876896473
업로드 잘됨여
뷰가 없어서 응답으로 캡처본 대신합니다.

[Feat/#365] 상세이미지 업로드 서버 연결

---

src/components/commons/button/Button.styled.ts
src/components/commons/button/Button.tsx
src/pages/lookup/components/LookupCard.styled.ts
src/pages/lookup/components/LookupCard.tsx
src/pages/lookup/components/LookupWrapper.styled.ts
src/pages/lookup/components/LookupWrapper.tsx
src/pages/main/components/performance/Performance.styled.ts
src/pages/main/components/performance/Performance.tsx
src/pages/main/components/performance/PerformanceCard.styled.ts

- Closes #362 
어떤 변경 사항이 있나요?
- 디자인 측에서 xsmall 버튼 width를 유동적으로 사용하고 싶다고 요청하셔서 `<Button variant="line" size={{ width: "10.8rem", height: "3.6rem" }} >` 처럼 size에 width와 height를 주면 xsmall 폰트에 맞춰 사이즈 변경할 수 있도록 수정하였습니다!
- 서버에서 상태에 취소 추가해 주면 issue 하나 더 파서 관련해서 수정하겠습니다~
- 현재 공연이 끝나면 취소 버튼 비활성화 처리해 두었는데, 취소 상태 추가할 때 취소의 경우에도 버튼 비활성화 할 수 있도록 하겠습니다!

[Refactor/#362] 메인 및 예매 조회 UI 변경사항 반영

---

src/pages/gig/Gig.tsx
src/pages/gig/components/content/Content.tsx
src/pages/gig/components/detailImage/DetailImage.styled.ts
src/pages/gig/components/detailImage/DetailImage.tsx
src/pages/gig/components/performanceIntroduce/PerformanceIntroduce.styled.ts
src/pages/gig/components/performanceIntroduce/PerformanceIntroduce.tsx
src/pages/register/Register.tsx
src/typings/api/schema/index.ts

- Closes #370 
어떤 변경 사항이 있나요?
1. 상세 이미지 리스트인 performanceImageList를 props로 받는 DetailImage 컴포넌트를 추가했습니다!
- 예매하기 페이지의 step3 에서도 정상 동작하도록 테스트 해야합니다.

[Feat/#370] 상세 페이지에서 상세 이미지 뷰 추가

---

src/constants/bookingStatus.ts
src/pages/lookup/Lookup.tsx
src/pages/lookup/components/LookupCard.styled.ts
src/pages/lookup/components/LookupCard.tsx
src/pages/lookup/components/LookupWrapper.tsx
src/pages/lookup/types/lookupType.ts

- Closes #372 
어떤 변경 사항이 있나요?
- 딱히 전달 사항은 없구,,, 예매 조회 페이지 내 취소 상태 추가했으며 취소 시에 취소하기 버튼과 계좌번호 버튼 비활성화 했습니다!
- 기존에 사용하는 색이 두 가지 뿐이었어서 그냥 컴포넌트 두 개 만들었는데 컴포넌트 세 개를 쓰는 건 비효율적인 것 같아서 status에 따라서 색 변하도록 설정했습니다!
- **코드리뷰 반영 사항** :  `bookingStatusText` 관련해서 공통으로 빼는 게 더 좋을 것 같다는 코드리뷰가 있어 반영했습니다!! bookingStatus API 사용하는 페이지 있다면 저기서 사용하면 좋을 것 같아요~

[Feat/#372] 예매 조회 페이지 취소 상태 추가

---

src/pages/gig/components/showInfo/ShowInfo.styled.ts
src/pages/gig/components/showInfo/ShowInfo.tsx

- Closes #385 
어떤 변경 사항이 있나요?
1. 원본 이미지 보이도록 구현
- 도영오빠가 작성한 코드 좀 만지작거렸어여..

[Feat/#385] 이미지 원본 보여주기

---

src/components/layout/Layout.tsx
src/hooks/useTokenRefresher.tsx
src/routes/Router.tsx

- Closes #400 
어떤 변경 사항이 있나요?
1. API 스펙이 변경되며 기존의 존재하는 만료된 엑세스 토큰을 함께 넣어서 요청을 보내면 500에러가 발생하고 있는 상황입니다.
따라서, 인터셉터로 500에러 발생시 토큰을 제거하는 작업을 진행하였습니다.
-

[HOTFIX/#400] TokenRefresher 훅 추가

---

src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #394 
어떤 변경 사항이 있나요?
1. 작업 내용
- 예매자 관리 페이지에서 CSV 다운로드 시 이전 CSV 데이터가 남아있던 문제가 발생했습니다.
-  모듈 스코프로 선언되어 파일을 로딩할 때만 초기화되던 CSVDataArr를 state로 변경하고,
-  map을 돌며 데이터를 임시로 넣을 tempCSVDataArr를 사용 -> tempCSVDataArr로 CSVDataArr를 초기화 하는 방식으로 해결했습니다.
**수정 전** 
**수정 후**

[Bug/#394] CSV 버그 수정

---

src/pages/ticketholderlist/TicketHolderList.tsx
src/pages/ticketholderlist/components/managercard/ManagerCard.tsx

- Closes #396 
어떤 변경 사항이 있나요?
1. 작업 내용
- 클릭 영역을 확대했습니다. 
- 새로고침 후 편집 -> 닫기 버튼 클릭 시 데이터가 렌더링 되지 않던 버그를 수정했습니다.
- 편집 모드 & 미입금 상태일 때만 클릭이 가능하도록 로직을 추가했습니다. 
**기존의 클릭 가능 영역**
**변경된 클릭 가능 영역**

[Feat/#396] 예매자 선택 영역 확장 + 데이터 렌더링 안되던 버그 수정

---

src/apis/domains/users/queries.ts
src/hooks/useTokenRefresher.tsx
src/stores/user.ts
src/typings/api/schema/index.ts
src/typings/userType.ts

- Closes #402 
어떤 변경 사항이 있나요?
1. API 스펙이 변경됨에 따라 500에러 -> 로그아웃 시키는 closed https://github.com/TEAM-BEAT/BEAT-Client/issues/400 로직을
role 유무에 따라 로그아웃 처리하도록 변경합니다.
-

[Refactor/#402] 로컬 스토리지의 role 여부에 따라, 저장된 로그인 여부 clear 하도록 수정

---

src/pages/myRegisterdShow/components/registeredcard/RegisteredCard.tsx
src/pages/ticketholderlist/TicketHolderList.tsx
src/pages/ticketholderlist/components/managercard/ManagerCard.tsx

- Closes #398 
어떤 변경 사항이 있나요?
1. 작업 내용
- 종료된 공연일 경우, 수정 페이지에 접근이 불가능하도록 구현했습니다.
- 수정 자체를 막으려면 서버 측 작업이 필요하여 요청해두겠습니다.

[Feat/#398] 종료된 공연 수정 막기

---

src/pages/book/Book.tsx
src/pages/gig/Gig.tsx

- Closes #429 
어떤 변경 사항이 있나요?
1. 지금까지는 맨 마지막의 공연 여부를 확인해서 예매 페이지의 접근 여부를 확인했었는데, 
이 방법으로는 마지막 공연이 예매가 불가능하면, 예매 페이지로의 접근 후, 이전 공연을 예매하지 못해
모든 공연의 예매 가능 여부를 확인하는 로직으로 변경하였습니다.
-
[상세 공연 조회 페이지]
[모든 공연이 매진 혹은 종료 이후, 예매 페이지 접근 시]

[Fix/#429] 예약 페이지에서 모든 스케쥴의 예매 가능 여부를 확인하도록 수정

---

src/apis/domains/performances/queries.ts
src/pages/modifyManage/ModifyMaker.tsx
src/pages/modifyManage/ModifyManage.tsx
src/pages/modifyManage/components/RoleLayout.tsx
src/pages/modifyManage/components/RoleWrapper.tsx
src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #433 
어떤 변경 사항이 있나요?
1. 작업 내용
cast 미리보기에 안 뜨던 원인은 다음과 같습니다.
1. dataState를 fetch해올 때, castList나 staffList 배열의 length가 0인 경우 id를 -1로 갖는 cast 혹은 staff로 초기화
2. 1번으로 인해 modifyManage에서 step 2로 가면 기본적으로 데이터를 추가할 수 있는 형태로 되어 있음
즉, 아래와 같은 모습(a)이 아니라
이와 같은 모습(b)을 보임 (의도된 디자인이었던 것으로 기억)
3. 그러나 modifyManage에서 cast 부분은 id == -1일 경우 뜨지 않게 되어 있었음 -> 수정 (커밋 내역 참고)
4. (a)의 같은 모습에서 추가할 경우에는, id에 new Date.now()가 들어감. -> 그래도, isNew 변수로 걸러낼 수 있음
(만약 -1이었으면 isNew가 없기 때문에 undefined가 뜨는 문제 발생)
이미 반영 잘 되고 있음.
다운 시간도 써달라고 했는데, 살짝 로직을 틀어야해서 그건 나중에 하겠습니다.

[Bug/#433] '공연 수정하기' 에서 cast 미리보기 안 뜨는 문제 + 추가된 회차에 예매한 경우 csv에 반영 안되는 문제

---

src/App.css
src/App.tsx
src/components/commons/hamburger/Hamburger.styled.ts

- #436 
- merge하고 모바일에서 확인해야 해서 제대로 실행되면 이슈 제가 따로 닫겠습니다! 해결 안 되면 같은 이슈 번호 계속 쓸게요 ㅠㅠ
어떤 변경 사항이 있나요?
1. vh -> dvh로 변경
<table align="center">
<tr align="center">
<th>하단바 있을 때</th>
<th>하단바 없을 때</th>
</tr>
<tr>
<td><img width="277" alt="image" src="https://github.com/user-attachments/assets/38fa1f33-68b8-4980-838a-818327d26d71"></td>
<td><img width="308" alt="image" src="https://github.com/user-attachments/assets/922e27f5-4e6e-4bb8-a7b6-7a9b7f02bd38"></td>
</tr>
</table>
위 이미지처럼, 사파리 자체 하단바까지 뷰포트로 계산해 사이드바 호출 시 하단이 잘리는 문제가 발견됐습니다!!
사실 기본 세팅은 하단바는 뷰포트로 계산하지 않는 게 기본인데, 이로 인해서 로그아웃 버튼이 하단바 아래로 사라지는 이슈가 있어서 [100vh로 맞추기](https://velog.io/@eunddodi/React-%EB%AA%A8%EB%B0%94%EC%9D%BC-%EC%9B%B9-%EC%95%B1-100vh-%EC%8B%A4%EC%A0%9C-%ED%99%94%EB%A9%B4-%ED%81%AC%EA%B8%B0%EB%A1%9C-%EB%A7%9E%EC%B6%94%EA%B8%B0) …

[Fix/#436] 사이드바 하단 잘리는 오류 수정

---

src/components/commons/bottomSheet/BottomSheet.styled.ts
src/components/commons/bottomSheet/BottomSheet.tsx

- Closes #450
어떤 변경 사항이 있나요?
바텀시트 상단 padding값이 고정인데, 이번 스프린트에 상단 padding 값이 달라지는 바텀시트가 두 개 들어와서 바텀시트 상단 padding 값을 props로 조정할 수 있도록 변경하였습니다.
무조건 상단 padding이 3.6rem인데, 3.2rem과 1.2rem이 생겼습니다. ㅠㅠ

[ Refactor/#450 ] Bottom Sheet 상단 padding값 변경 가능하도록 변경

---

src/pages/gig/components/peopleCard/PeopleCard.tsx
src/pages/modifyManage/ModifyMaker.tsx
src/pages/modifyManage/ModifyManage.tsx
src/pages/register/Register.tsx
src/pages/register/RegisterMaker.tsx

- Closes #455 
어떤 변경 사항이 있나요?
1. 공연 소개, 유의사항 글자수 변경
2. 공연진 사진 선택으로 변
-

[Feat/#455] 공연 등록, 수정 변경사항 반영

---

src/hooks/useTokenRefresher.tsx
src/routes/AuthRequierd.tsx
src/routes/Router.tsx

[HOTFIX/#464] auth 페이지로 navigate 되는 로직 수정

---

src/components/commons/mapInput/MapInput.styled.ts
src/components/commons/toast/Toast.styled.ts
src/components/commons/toast/Toast.tsx
src/pages/cancel/Cancel.tsx
src/pages/gig/components/performanceIntroduce/PerformanceIntroduce.tsx
src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #470 
어떤 변경 사항이 있나요?
1. 작업 내용
- 토스트를 편하게 사용할 수 있도록 handleToastVisible 함수를 작성해두었습니다.
추후 유틸 함수로 분리하여 export 해서 사용하는 것도 좋을 것 같습니다! 
스크린샷을 보면, 토스트의 배경색이나 위치가 다른 것을 확인할 수 있습니다. 그래서 기존의 Toast 공통 컴포넌트를 기존의 사용 방법에서 포지션을 옵셔널로 정할 경우, 그에 맞게 top용 토스트로 변하도록 개선했습니다.

[Feat/#470] 토스트 개선, 토스트 유틸 함수 구현, QA 반영

---

src/assets/svgs/BtnFilter.tsx
src/pages/ticketholderlist/TicketHolderList.styled.ts
src/pages/ticketholderlist/TicketHolderList.tsx
src/pages/ticketholderlist/components/FilterBottomSheet/FilterBottomSheet.styled.ts
src/pages/ticketholderlist/components/FilterBottomSheet/FilterBottomSheet.tsx
src/pages/ticketholderlist/components/manageCard/ManageAccount.tsx
src/pages/ticketholderlist/components/manageCard/ManageCheckBox.styled.ts
src/pages/ticketholderlist/components/searchBar/SearchBar.tsx

- Closes #462 
어떤 변경 사항이 있나요?
- 스크롤 위로 쭉 당겼을 때 cta 버튼 양옆으로 여백 나오는 오류 해결
-> 카카오웹 이슈로 확인했습니다...!! 
- 버튼 텍스트 중앙 정렬 필요
-> 확인해봤는데 중앙 정렬이 아니라 폰트 이슈인 것 같아요... 지금 메인도 다 글지 위로 치우쳐져 있고 처음엔 정렬 맞는데 3초 뒤에 안 맞음 ㅠㅠ
- 모바일에서 필터 svg 찌그러지는 오류 해결
-> 일단 해결해보긴 했는데 데스크탑에선 확인이 불가능해서 머지하고 다시 확인하겠습니다!

[Fix/#462] 자잘한 디자인 QA + 변경사항 반영

---

src/components/commons/bottomSheet/actionsBottomSheet/phoneNumber/PhoneNumber.tsx
src/components/commons/mapInput/MapInput.styled.ts
src/components/commons/mapInput/MapInput.tsx
src/components/commons/toast/Toast.tsx
src/hooks/index.ts
src/hooks/useToastHandler.ts
src/pages/book/components/paidBook/PaidBook.tsx
src/pages/cancel/Cancel.tsx
src/pages/gig/components/performanceIntroduce/Contact.tsx
src/pages/gig/components/performanceIntroduce/PerformanceIntroduce.tsx
src/pages/test/TestPage.tsx
src/pages/test/modalTest/BankAccount.tsx
src/pages/ticketholderlist/TicketHolderList.tsx

- Closes #481 
어떤 변경 사항이 있나요?
1. 작업 내용
- 추후 toast를 바텀으로 옮겨달라는 요청에 대비하여 toast의 bottom 속성은 살려두었습니다.
- 이에 따라, 메세지가 변하거나 toast의 위치가 유동적으로 변하는 경우에는 useToastHandler 훅을 사용하시면 됩니다.
- useToastHandler 에서는 toastConfig(메세지, 위치)와 toastVisible, handlerToastVisible 등을 반환합니다. 
- useToastHandler는 필수가 아닙니다. 다만 만약 사용할 경우, useToast는 사용할 필요가 없습니다.
이외에도 다른 qa 반영
- 필요 없는 alert 제거
- toast 전부 top으로 이동

[Feat/#481] useToastHandler 훅 추가, 토스트 전부 상단으로 위치 (+ alert 제거), 핑크색으로 글자 칠해지도록 기능 구현

---

src/pages/book/components/complete/Complete.tsx
src/pages/main/Main.tsx
src/pages/main/components/floating/Floating.tsx
src/pages/main/components/performance/Performance.tsx
src/pages/main/components/performance/PerformnaceCard.tsx
src/pages/onBoarding/OnBoarding.tsx
src/pages/register/Register.tsx
src/routes/Router.tsx
src/track/constants/events.ts
src/track/useTrackingPageView.ts

- Closes #501 
어떤 변경 사항이 있나요?
- 지우가 바로 사용 가능하냐고 해서 리뷰 없이 바로 main 머지할게요~!
- 현재 `Viewed_Page_{}` 가 페이지마다 달려 있는데 나중에 한 파일로 옮기면 좋을 것 같아요! 일단 지우가 당장 내일부터 사용하고 싶다고 해서 머지 후에 나중에 작업하겠습니다!
- 지금 신지바보 서버 닫혀서 프로덕션 서버로 작업햇어요... 개쫄림이슈로 테스트를 많이 못해봤습니다 ㅠㅠ

[Feat/#510] 메인 페이지, 공연 등록 페이지 관련 믹스패널 로깅
